
export const slides = [{
  image: '/banner-1.jpg',
  heading: 'Discover Your Perfect Fit',
  description: 'Premium quality undergarments for every occasion',
  buttonText: 'Shop Now',
  buttonLink: '#shop-now',
},
{
  image: '/banner-2.jpg',
  heading: 'Elegance Meets Comfort',
  description: 'Available all over Pakistan',
  buttonText: 'Shop Now',
  buttonLink: '#shop-now',
},
{
  image: '/banner-3.jpg',
  heading: 'Easy Returns',
  description: "Don't like it? Return it hassle-free!",
  buttonText: 'Learn More',
  buttonLink: '#return-policy',
},
]

export const policy = [
  {
    icon: 'fa-undo',
    title: 'Easy Returns',
    description: "Don't like what you received? Return it within 7 days!"
  },
  {
    icon: 'fa-truck',
    title: 'Free Pickup',
    description: "We'll pick up your return at no extra cost"
  },
  {
    icon: 'fa-money-bill-wave',
    title: 'Full Refund',
    description: 'Get your money back within 3-5 business days'
  }
]

export const products = [
  {
    name: 'Lace Bralette',
    price: '$29.99',
    image: '/banner-1.jpg',
  },
  {
    name: 'Silk Camisole',
    price: '$39.99',
    image: '/banner-2.jpg',
  },
  {
    name: 'Cotton Briefs',
    price: '$19.99',
    image: '/banner-3.jpg',
  },
  {
    name: 'Sleep Set',
    price: '$49.99',
    image: '/banner-1.jpg',
  }
]

export const category = [{
  text: 'Bras',
  image: '/banner-1.jpg',
},
{
  text: 'Panties',
  image: '/banner-2.jpg',
},
{
  text: 'Lingerie',
  image: '/banner-3.jpg',
},
{
  text: 'Sleepwear',
  image: '/banner-1.jpg',
}]

export const cartItems = [
  {
    id: "1",
    name: 'Q-EN Bamboo Camisole Black 705',
   category: 'Bras & Camisoles',
    price: 1700,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2','3','4'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: 'M',
  },
  {
    id: "2",
    name: 'Luxe Lace Bra',
   category: 'Bras & Camisoles',
    price: 3200,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-4 Days',
    area: 'Nationwide',
    origin: 'France',
    shippedBy: 'Ensemble',
    options: ['32B', '34B', '36C'],
    selectedOption: '34B',
  },
  {
    id: "3",
    name: 'Soft Cotton Briefs (Pack of 3)',
    category: 'Bras & Camisoles',
    price: 1400,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Pakistan',
    shippedBy: 'ComfortWear',
    options: ['S', 'M', 'L'],
    selectedOption: 'M',
  },
  {
    id: "4",
    name: 'Elegant Silk Nightwear Set',
  category: 'Bras & Camisoles',
    price: 4800,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '3-5 Days',
    area: 'Nationwide',
    origin: 'China',
    shippedBy: 'DreamLux',
    options: ['M', 'L', 'XL'],
    selectedOption: 'L',
  },
  {
    id: "5",
    name: 'Floral Mesh Lingerie Set',
  category: 'Bras & Camisoles',
    price: 3700,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-2 Days',
    area: 'Nationwide',
    origin: 'Turkey',
    shippedBy: 'Femine',
    options: ['S', 'M', 'L'],
    selectedOption: 'S',
  },
  {
    id: "6",
    name: 'Supportive Sports Bra',
   category: 'Bras & Camisoles',
    price: 2000,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2','3','4'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-4 Days',
    area: 'Nationwide',
    origin: 'USA',
    shippedBy: 'ActiveFit',
    options: ['S', 'M', 'L'],
    selectedOption: 'M',
  },
  {
    id: "7",
    name: 'Thermal Long Johns Set',
    category: 'Panties & Lingerie',
    price: 2500,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-3 Days',
    area: 'Nationwide',
    origin: 'Germany',
    shippedBy: 'HeatCore',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: 'L',
  },
  {
    id: "8",
    name: 'Maternity Nursing Bra',
  category: 'Panties & Lingerie',
    price: 2200,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'UK',
    shippedBy: 'BabyCare',
    options: ['M', 'L', 'XL'],
    selectedOption: 'M',
  },
  {
    id: "9",
    name: 'Classic Seamless Panties',
   category: 'Panties & Lingerie',
    price: 1800,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Vietnam',
    shippedBy: 'EverydayComfort',
    options: ['S', 'M', 'L'],
    selectedOption: 'L',
  },
  {
    id: "10",
    name: 'Basic Everyday Bra',
    category: 'Panties & Lingerie',
    price: 1700,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2','3','4'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'India',
    shippedBy: 'Naheed',
    options: ['32A', '34B', '36C'],
    selectedOption: '34B',
  },
  {
    id: "11",
    name: 'Modal Tank Top',
   category: 'Panties & Lingerie',
    price: 1900,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-4 Days',
    area: 'Nationwide',
    origin: 'Bangladesh',
    shippedBy: 'SoftLine',
    options: ['S', 'M', 'L'],
    selectedOption: 'M',
  },
  {
    id: "12",
    name: 'Lounge Shorts Set',
     category: 'Panties & Lingerie',
    price: 2100,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '3-5 Days',
    area: 'Nationwide',
    origin: 'Sri Lanka',
    shippedBy: 'ChillZone',
    options: ['M', 'L', 'XL'],
    selectedOption: 'L',
  },
  {
    id: "13",
    name: 'Q-EN Bamboo Camisole Black 705',
      category: 'Sleepwear & Loungewear',
    price: 1700,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2','3','4'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: 'M',
  },
  {
    id: "14",
    name: 'Luxe Lace Bra',
    category: 'Sleepwear & Loungewear',
    price: 3200,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-4 Days',
    area: 'Nationwide',
    origin: 'France',
    shippedBy: 'Ensemble',
    options: ['32B', '34B', '36C'],
    selectedOption: '34B',
  },
  {
    id: "15",
    name: 'Soft Cotton Briefs (Pack of 3)',
     category: 'Sleepwear & Loungewear',
    price: 1400,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Pakistan',
    shippedBy: 'ComfortWear',
    options: ['S', 'M', 'L'],
    selectedOption: 'M',
  },
  {
    id: "16",
    name: 'Elegant Silk Nightwear Set',
   category: 'Sleepwear & Loungewear',
    price: 4800,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '3-5 Days',
    area: 'Nationwide',
    origin: 'China',
    shippedBy: 'DreamLux',
    options: ['M', 'L', 'XL'],
    selectedOption: 'L',
  },
  {
    id: "17",
    name: 'Floral Mesh Lingerie Set',
    category: 'Sleepwear & Loungewear',
    price: 3700,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-2 Days',
    area: 'Nationwide',
    origin: 'Turkey',
    shippedBy: 'Femine',
    options: ['S', 'M', 'L'],
    selectedOption: 'S',
  },
  {
    id: "18",
    name: 'Supportive Sports Bra',
     category: 'Sleepwear & Loungewear',
    price: 2000,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2','3','4'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-4 Days',
    area: 'Nationwide',
    origin: 'USA',
    shippedBy: 'ActiveFit',
    options: ['S', 'M', 'L'],
    selectedOption: 'M',
  },
  {
    id: "19",
    name: 'Thermal Long Johns Set',
     category: 'Specialty Wear',
    price: 2500,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-3 Days',
    area: 'Nationwide',
    origin: 'Germany',
    shippedBy: 'HeatCore',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: 'L',
  },
  {
    id: "20",
    name: 'Maternity Nursing Bra',
    category: 'Specialty Wear',
    price: 2200,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'UK',
    shippedBy: 'BabyCare',
    options: ['M', 'L', 'XL'],
    selectedOption: 'M',
  },
  {
    id: "21",
    name: 'Classic Seamless Panties',
     category: 'Specialty Wear',
    price: 1800,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Vietnam',
    shippedBy: 'EverydayComfort',
    options: ['S', 'M', 'L'],
    selectedOption: 'L',
  },
  {
    id: "22",
    name: 'Basic Everyday Bra',
   category: 'Specialty Wear',
    price: 1700,
    image: '/banner-1.jpg',
    availableQuantities: ['1','2','3','4'],
    selectedQuantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'India',
    shippedBy: 'Naheed',
    options: ['32A', '34B', '36C'],
    selectedOption: '34B',
  },
  {
    id: "23",
    name: 'Modal Tank Top',
   category: 'Specialty Wear',
    price: 1900,
    image: '/banner-2.jpg',
    availableQuantities: ['1','2','3'],
    selectedQuantity: 1,
    stock: true,
    delivery: '2-4 Days',
    area: 'Nationwide',
    origin: 'Bangladesh',
    shippedBy: 'SoftLine',
    options: ['S', 'M', 'L'],
    selectedOption: 'M',
  },
  {
    id: "24",
    name: 'Lounge Shorts Set',
    category: 'Specialty Wear',
    price: 2100,
    image: '/banner-3.jpg',
    availableQuantities: ['1','2'],
    selectedQuantity: 1,
    stock: true,
    delivery: '3-5 Days',
    area: 'Nationwide',
    origin: 'Sri Lanka',
    shippedBy: 'ChillZone',
    options: ['M', 'L', 'XL'],
    selectedOption: 'L',
  }
];
